export const SET_CONFIGURATION = "SET_CONFIGURATION";
export const SET_GAME_IN_PROGRESS = "SET_GAME_IN_PROGRESS";
export const SET_TIMER = "SET_TIMER";
export const SET_HIGH_SCORES = "SET_HIGH_SCORES";
